version: 0.0
os: linux
files:
  - source: scripts/index.html
    destination: /usr/share/nginx/html/
    overwrite: true
hooks:
  AfterInstall:
    - location: scripts/restart_script.sh
      timeout: 300
      runas: root
