version: 0.0
os: linux
files:
  - source: index.html
    destination: /usr/share/nginx/html/
    overwrite: true
file_exists_behavior: OVERWRITE
hooks:
  AfterInstall:
    - location: scripts/restart_script.sh
      timeout: 300
      runas: root
